---
- hosts: all

  tasks:
  - name: Add the user "youcefadmin"
    become: true
    user:
      name: youcefadmin

  - name: "Deploy package htop"
    become: true
    package:
      name: htop
      state: present

  - name: "Deploy package vim"
    become: true
    package:
      name: vim
      state: present

  - name: "SSH authorized key for youcefadmin"
    become: true
    authorized_key:
      user: youcefadmin
      state: present
      key: "{{ lookup('file', '/home/itesciadmin/.ssh/id_rsa.pub') }}"
