---
- hosts: all
  vars:
    new_user_name: youcefadmin
    ssh_authorized_user: youcefadmin
  vars_prompt:
    - name: new_user_name
      prompt: "What is the username of the new user?"
      private: no

    - name: ssh_authorized_user
      prompt: "What is the username of the user to authorize with SSH?"
      private: no

  tasks:
  - name: Add the user new_user_name
    become: true
    user:
      name: "{{ new_user_name }}"

  - name: Deploy package htop
    become: true
    package:
      name: htop
      state: present

  - name: Deploy package vim
    become: true
    package:
      name: vim
      state: present

  - name: SSH authorized key for ssh_authorized_user
    become: true
    authorized_key:
      user: "{{ ssh_authorized_user }}"
      state: present
      key: "{{ lookup('file', 'keys/id_rsa.pub') }}"
