- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

    reload: True

- name: Masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: ens39
    jump: MASQUERADE
  become: yes

- name: Forward port to host
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ens39
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: DNAT
    to_destination: "{{ item.ip }}":"{{ item.port }}"
  become: yes
  with_items:
    - {ip: 10.0.0.102, port: 53, protocol: udp}
    - {ip: 10.0.0.202, port: 25, protocol: tcp}

- name: Accept
  iptables:
    chain: FORWARD
    in_interface: ens39
    protocol: "{{ item.protocol }}"
    destination_port: 53
    jump: ACCEPT
  become: yes
  with_items:
    - {ip: 10.0.0.102, port: 53, protocol: udp}
    - {ip: 10.0.0.202, port: 25, protocol: tcp}

