- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True

- name: Masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ item.interface }}"
    jump: MASQUERADE
  become: yes
  with_items:
     - "{{ dns }}"
     - "{{ smtp }}"

- name: Forward port to dns
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ item.interface }}"
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: DNAT
    to_destination: "{{ item.to_destination }}"
  become: yes
  with_items:
     - "{{ dns }}"
     - "{{ smtp }}"

- name: Accept
  iptables:
    chain: FORWARD
    in_interface: "{{ item.interface }}"
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  become: yes
  with_items:
     - "{{ dns }}"
     - "{{ smtp }}"

